// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ7rU84aVkZQJAfhKqC68uLQzkn9bQy-Q',
    appId: '1:123477866850:web:d03a0c951329a6645bd43b',
    messagingSenderId: '123477866850',
    projectId: 'kazi-kazi-860b9',
    authDomain: 'kazi-kazi-860b9.firebaseapp.com',
    storageBucket: 'kazi-kazi-860b9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3MgdVDEZdsy_YxnFKUR3zrXArRm7hy7A',
    appId: '1:123477866850:android:178d47adb6cb360e5bd43b',
    messagingSenderId: '123477866850',
    projectId: 'kazi-kazi-860b9',
    storageBucket: 'kazi-kazi-860b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeuGanuu1hYohNhR_f84fobK6DQIJfP_Y',
    appId: '1:123477866850:ios:99cd00ae2025d6365bd43b',
    messagingSenderId: '123477866850',
    projectId: 'kazi-kazi-860b9',
    storageBucket: 'kazi-kazi-860b9.firebasestorage.app',
    iosBundleId: 'com.example.kazikazi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeuGanuu1hYohNhR_f84fobK6DQIJfP_Y',
    appId: '1:123477866850:ios:99cd00ae2025d6365bd43b',
    messagingSenderId: '123477866850',
    projectId: 'kazi-kazi-860b9',
    storageBucket: 'kazi-kazi-860b9.firebasestorage.app',
    iosBundleId: 'com.example.kazikazi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ7rU84aVkZQJAfhKqC68uLQzkn9bQy-Q',
    appId: '1:123477866850:web:178f8d358e05cbdf5bd43b',
    messagingSenderId: '123477866850',
    projectId: 'kazi-kazi-860b9',
    authDomain: 'kazi-kazi-860b9.firebaseapp.com',
    storageBucket: 'kazi-kazi-860b9.firebasestorage.app',
  );
}
